name: Build Mac .app

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Kodları klonla
      uses: actions/checkout@v3

    - name: Python ortamını kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli paketleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: .app oluştur
      run: |
        python setup.py py2app

    - name: .app dosyasını artefact olarak yükle
      uses: actions/upload-artifact@v3
      with:
        name: TesTimaGeNB-macOS-app
        path: dist/*.app
